create user 'mysql_async'@'%' IDENTIFIED BY 'password';
create user 'mysql_async_old'@'%' IDENTIFIED BY 'password';
create user 'mysql_async_nopw'@'%' IDENTIFIED BY 'password';
create database mysql_async_tests;
create table mysql_async_tests.transaction_test (id varchar(255) not null, primary key (id));
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_old'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'mysql_async_old'@'%' = PASSWORD('do_not_use_this');
SET PASSWORD FOR 'mysql_async_nopw'@'%' = PASSWORD('');
flush privileges;
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_nopw'@'%' WITH GRANT OPTION;